language: python
python:
  - "2.7"
env: PGVERSION=9.2
sudo: required
cache: pip
before_install:
  - chmod +x ./bin/travis-install-dependencies.bash
  - chmod +x ./bin/travis-run-tests.sh
install: ./bin/travis-install-dependencies.bash
script:
  - ./bin/travis-run-tests.sh
after_success:
  - coveralls
